version: '3.8'

services:
  recibolegal:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.production
    restart: unless-stopped
    volumes:
      - receipts_data:/app/receipts
    networks:
      - recibolegal_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recibolegal.rule=Host(`recibolegal.com.br`) || Host(`www.recibolegal.com.br`)"
      - "traefik.http.routers.recibolegal.tls=true"
      - "traefik.http.routers.recibolegal.tls.certresolver=letsencrypt"
      - "traefik.http.services.recibolegal.loadbalancer.server.port=3001"

  traefik:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=felipecasali@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    restart: unless-stopped
    networks:
      - recibolegal_network

volumes:
  receipts_data:
  traefik_letsencrypt:

networks:
  recibolegal_network:
    driver: bridge
